name: pink
channels:
    - conda-forge
dependencies:
    - pinocchio >=3.0.0
    - pink
    - pip >=21.3.1
    - pip:
        - sphinx >= 7.2.2
        - sphinx-autodoc-typehints
        - sphinx-favicon
        - sphinx-mathjax-offline
        - sphinx_rtd_theme
